"""API key management utilities."""

import os
import sys
from pathlib import Path
from typing import Dict, Optional


def get_env_file_path() -> Path:
    """Get the path to the .env file."""
    return Path(__file__).parent.parent.parent / '.env'


def load_env_file() -> Dict[str, str]:
    """Load existing .env file if it exists."""
    env_path = get_env_file_path()
    env_vars = {}

    if env_path.exists():
        with open(env_path, 'r') as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith('#') and '=' in line:
                    key, value = line.split('=', 1)
                    env_vars[key.strip()] = value.strip().strip('"\'')

    return env_vars


def save_env_file(env_vars: Dict[str, str]):
    """Save environment variables to .env file."""
    env_path = get_env_file_path()

    with open(env_path, 'w') as f:
        f.write("# Cradle API Keys Configuration\n")
        f.write("# Generated by setup.py\n\n")

        # Write OpenAI keys
        if 'OA_OPENAI_KEY' in env_vars or 'AZ_OPENAI_KEY' in env_vars:
            f.write("# OpenAI Configuration\n")
            if 'OA_OPENAI_KEY' in env_vars:
                f.write(f"OA_OPENAI_KEY={env_vars['OA_OPENAI_KEY']}\n")
            if 'AZ_OPENAI_KEY' in env_vars:
                f.write(f"AZ_OPENAI_KEY={env_vars['AZ_OPENAI_KEY']}\n")
            if 'AZ_BASE_URL' in env_vars:
                f.write(f"AZ_BASE_URL={env_vars['AZ_BASE_URL']}\n")
            f.write("\n")

        # Write Claude keys
        if 'OA_CLAUDE_KEY' in env_vars or 'RF_CLAUDE_AK' in env_vars:
            f.write("# Claude Configuration\n")
            if 'OA_CLAUDE_KEY' in env_vars:
                f.write(f"OA_CLAUDE_KEY={env_vars['OA_CLAUDE_KEY']}\n")
            if 'RF_CLAUDE_AK' in env_vars:
                f.write(f"RF_CLAUDE_AK={env_vars['RF_CLAUDE_AK']}\n")
            if 'RF_CLAUDE_SK' in env_vars:
                f.write(f"RF_CLAUDE_SK={env_vars['RF_CLAUDE_SK']}\n")
            f.write("\n")

        # Write other settings
        if 'IDE_NAME' in env_vars:
            f.write("# Development Configuration\n")
            f.write(f"IDE_NAME={env_vars['IDE_NAME']}\n")

    print(f"✓ Saved configuration to {env_path}")


def validate_openai_key(api_key: str) -> bool:
    """Validate OpenAI API key by making a test call."""
    try:
        import openai
        client = openai.OpenAI(api_key=api_key)

        # Test with a minimal embedding call (cheap)
        response = client.embeddings.create(
            model="text-embedding-ada-002",
            input="test"
        )
        return True
    except Exception as e:
        print(f"   ❌ Invalid OpenAI key: {str(e)[:100]}")
        return False


def validate_claude_key(api_key: str) -> bool:
    """Validate Claude API key by making a test call."""
    try:
        import anthropic
        client = anthropic.Anthropic(api_key=api_key)

        # Test with a minimal message call
        message = client.messages.create(
            model="claude-3-5-sonnet-20241022",
            max_tokens=10,
            messages=[{"role": "user", "content": "Hi"}]
        )
        return True
    except Exception as e:
        print(f"   ❌ Invalid Claude key: {str(e)[:100]}")
        return False


def prompt_for_api_keys(existing_vars: Optional[Dict[str, str]] = None) -> Dict[str, str]:
    """Interactively prompt for API keys."""
    if existing_vars is None:
        existing_vars = {}

    env_vars = existing_vars.copy()

    print("\n" + "=" * 60)
    print("🔑 API Key Configuration")
    print("=" * 60)
    print("\nCradle requires at least one LLM provider.")
    print("You can configure OpenAI, Claude, or both.\n")

    # OpenAI
    print("1️⃣  OpenAI Configuration")
    print("-" * 40)

    current_openai = existing_vars.get('OA_OPENAI_KEY', '')
    if current_openai:
        print(f"Current key: {current_openai[:10]}...{current_openai[-4:]}")
        use_existing = input("Keep existing OpenAI key? (Y/n): ").strip().lower()
        if use_existing != 'n':
            pass  # Keep existing
        else:
            current_openai = ''

    if not current_openai:
        openai_key = input("Enter OpenAI API key (or press Enter to skip): ").strip()
        if openai_key:
            print("   Validating key...", end='', flush=True)
            if validate_openai_key(openai_key):
                print(" ✓")
                env_vars['OA_OPENAI_KEY'] = openai_key
            else:
                print(" ✗ (key not saved)")
        else:
            print("   Skipped OpenAI configuration")

    # Azure OpenAI (optional)
    azure_key = input("\nEnter Azure OpenAI key (or press Enter to skip): ").strip()
    if azure_key:
        azure_url = input("Enter Azure base URL: ").strip()
        env_vars['AZ_OPENAI_KEY'] = azure_key
        env_vars['AZ_BASE_URL'] = azure_url

    print("\n2️⃣  Claude Configuration")
    print("-" * 40)

    current_claude = existing_vars.get('OA_CLAUDE_KEY', '')
    if current_claude:
        print(f"Current key: {current_claude[:10]}...{current_claude[-4:]}")
        use_existing = input("Keep existing Claude key? (Y/n): ").strip().lower()
        if use_existing != 'n':
            pass  # Keep existing
        else:
            current_claude = ''

    if not current_claude:
        claude_key = input("Enter Claude API key (or press Enter to skip): ").strip()
        if claude_key:
            print("   Validating key...", end='', flush=True)
            if validate_claude_key(claude_key):
                print(" ✓")
                env_vars['OA_CLAUDE_KEY'] = claude_key
            else:
                print(" ✗ (key not saved)")
        else:
            print("   Skipped Claude configuration")

    # AWS Claude (optional)
    aws_ak = input("\nEnter AWS Access Key for Claude (or press Enter to skip): ").strip()
    if aws_ak:
        aws_sk = input("Enter AWS Secret Key: ").strip()
        env_vars['RF_CLAUDE_AK'] = aws_ak
        env_vars['RF_CLAUDE_SK'] = aws_sk

    # IDE configuration
    print("\n3️⃣  Development Configuration")
    print("-" * 40)
    print("IDE name for window switching (Code for VSCode, PyCharm, etc.)")
    ide = input("Enter IDE name (default: Code): ").strip() or "Code"
    env_vars['IDE_NAME'] = ide

    # Validate at least one provider
    has_openai = 'OA_OPENAI_KEY' in env_vars or 'AZ_OPENAI_KEY' in env_vars
    has_claude = 'OA_CLAUDE_KEY' in env_vars or 'RF_CLAUDE_AK' in env_vars

    if not (has_openai or has_claude):
        print("\n⚠️  Warning: No LLM provider configured!")
        print("   You need at least one provider to run Cradle.")
        cont = input("\nSave anyway? (y/N): ").strip().lower()
        if cont != 'y':
            sys.exit(1)

    return env_vars


def interactive_setup():
    """Run interactive API key setup."""
    print("\n🎮 Cradle API Key Setup")
    print("=" * 60)

    # Load existing keys
    existing = load_env_file()

    if existing:
        print("\nFound existing .env file.")
        choice = input("Update existing keys or start fresh? (update/fresh): ").strip().lower()
        if choice == 'fresh':
            existing = {}

    # Prompt for keys
    env_vars = prompt_for_api_keys(existing)

    # Save
    save_env_file(env_vars)

    print("\n✅ API key configuration complete!")
    print(f"   OpenAI: {'✓' if 'OA_OPENAI_KEY' in env_vars else '✗'}")
    print(f"   Claude: {'✓' if 'OA_CLAUDE_KEY' in env_vars else '✗'}")


if __name__ == '__main__':
    interactive_setup()
